version: "3"
services:
  visualizer:
    image: alexellis2/visualizer-arm:0.3
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager ]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
